export GOOGLE_APPLICATION_CREDENTIALS="gcp/fusemachineschat.json"
python parlai/scripts/train_model.py \
--gcs-train-path "train-temp-2" \
-t fromfile --fromfile_datapath /tmp/train_path/train_data.txt \
-m transformer/generator \
--init-model zoo:blender/blender_90M/model \
--dict-file zoo:blender/blender_90M/model.dict \
--load-from-checkpoint True \
--run-tag blenderbot_90M_default \
--embedding-size 512 --n-layers 8 --ffn-size 2048 \
--dropout 0.1 --n-heads 16 \
--learn-positional-embeddings True \
--n-positions 512 --variant xlm \
--activation gelu --skip-generation True \
--fp16 True --text-truncate 512 \
--label-truncate 128 --dict-tokenizer bpe \
--dict-lower True -lr 1e-06 --optimizer adamax \
--lr-scheduler reduceonplateau --gradient-clip 0.1 \
-veps 0.25 --betas 0.9,0.999 --update-freq 1 \
--attention-dropout 0.0 --relu-dropout 0.0 \
--skip-generation True -mcs all -vp 15 -stim 60 \
-vme 20000 -bs 16 -vmt ppl -vmm min \
--save-after-valid True \
--model-file /tmp/test_train_90M \
-tblog True